### PR TITLE
fix-sprockets3-support

### PR DESCRIPTION
**Pull request by gafrom**
Hi, let's add support for sprockets 3.

### CODE REVIEW

**Comment by gafrom** [comment]
Checks failed due to Travis bundler version [issue](https://github.com/rubygems/rubygems/issues/1419).
Everything else seems to work fine

**Comment by mahnunchik** [comment]
We are really need this feature :+1:

**Comment by aaronjensen** [comment]
Thanks!

**Comment by aaronjensen** [comment]
@gafrom @mahnunchik I had to revert this. The tests don't actually pass because the newest sprockets does not include tilt, which this package relies on. If you want to, you can resubmit a pull request to address this, I don't have the time right now to look into what the new method for processors is.

**Pull request merged**
